kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: finance-users-clusterview
subjects:
  - kind: ServiceAccount
    name: finance-user
    namespace: finance
roleRef:
  kind: ClusterRole
  name: view 
  apiGroup: rbac.authorization.k8s.io