kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: finance-admin
  namespace: finance
subjects:
  - kind: ServiceAccount 
    name: finance-user
roleRef:
  kind: Role
  name: finance-admin
  apiGroup: rbac.authorization.k8s.io