kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: humanresources-users-clusterview
subjects:
  - kind: ServiceAccount
    name: humanresources-user
    namespace: humanresources
roleRef:
  kind: ClusterRole
  name: view 
  apiGroup: rbac.authorization.k8s.io