kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: humanresources-admin
  namespace: humanresources
subjects:
  - kind: ServiceAccount 
    name: humanresources-user
roleRef:
  kind: Role
  name: humanresources-admin
  apiGroup: rbac.authorization.k8s.io